name: easy_peasy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.2
  shared_preferences: ^2.0.12
  firebase_auth:
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.4
  get:
  firebase_messaging_platform_interface: ^3.5.1
  firebase_storage_platform_interface: ^4.1.7
  cloud_functions_platform_interface: ^5.1.7
  cloud_firestore_platform_interface: ^5.5.7
  firebase_auth_platform_interface: ^6.2.7
  firebase_database_platform_interface: ^0.2.1+7
  image_picker: ^0.8.4+11
  firebase_storage: ^10.2.7
  cached_network_image: ^3.2.0
  flutter_cache_manager: ^3.3.0
  flip_card: ^0.6.0
  audioplayers: ^0.20.1
  animated_toggle_switch: ^0.5.2
  confetti: ^0.6.0
  cloud_firestore: ^3.1.8
  achievement_view: ^1.0.0
  fluttertoast: ^8.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/icons/app_icon/
    - assets/logo/
