name: easy_peasy
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  google_fonts: ^2.2.0
  flutter_svg: ^1.0.3
  shared_preferences: ^2.0.12
  firebase_auth: ^3.3.8
  firebase_core: ^1.12.0
  google_sign_in: ^5.2.4
  font_awesome_flutter: ^9.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons:

flutter_icons:
  android: true
  image_path: "assets/icons/app_icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/onboarding/
    - assets/icons/app_icon/
    - assets/logo/
